{
 "title": "Chogori-SQL",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "query": ".*1000[56].*" }
  ]
 },
 "panels": [
  {
   "title": "Write Latency (usec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(write_op_latency_bucket[15s])) by(le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(write_op_latency_bucket[15s])) by(le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(write_op_latency_bucket[15s])) by(le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1.0, sum(irate(write_op_latency_bucket[15s])) by(le))",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "Write Count/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(write_op_latency_count[15s]))/5"
    }
   ]
  },
  {
   "title": "Read Latency (usec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(read_op_latency_bucket[15s])) by(le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(read_op_latency_bucket[15s])) by(le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(read_op_latency_bucket[15s])) by(le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1.0, sum(irate(read_op_latency_bucket[15s])) by(le))",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "Read Count/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(read_op_latency_count[15s]))/5"
    }
   ]
  },
  {
   "title": "Scan Latency (usec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(scan_op_latency_bucket[15s])) by(le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(scan_op_latency_bucket[15s])) by(le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(scan_op_latency_bucket[15s])) by(le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1.0, sum(irate(scan_op_latency_bucket[15s])) by(le))",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "Scan Count/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scan_op_latency_count[15s]))/5"
    }
   ]
  },
  {
   "title": "Txn Latency (usec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(txn_latency_bucket[15s])) by(le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(txn_latency_bucket[15s])) by(le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(txn_latency_bucket[15s])) by(le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1.0, sum(irate(txn_latency_bucket[15s])) by(le))",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "Txn Count/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(txn_latency_count[15s]))/5"
    }
   ]
  },
  {
   "title": "Txn Begin Latency (usec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(txn_begin_latency_bucket[15s])) by(le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(txn_begin_latency_bucket[15s])) by(le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(txn_begin_latency_bucket[15s])) by(le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1.0, sum(irate(txn_begin_latency_bucket[15s])) by(le))",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "Txn End Latency (usec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(txn_end_latency_bucket[15s])) by(le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(txn_end_latency_bucket[15s])) by(le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(txn_end_latency_bucket[15s])) by(le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1.0, sum(irate(txn_end_latency_bucket[15s])) by(le))",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "Total Txn Ops",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(txn_ops_bucket[15s])) by(le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(txn_ops_bucket[15s])) by(le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(txn_ops_bucket[15s])) by(le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1.0, sum(irate(txn_ops_bucket[15s])) by(le))",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "Total Txn Read Ops",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(txn_read_ops_bucket[15s])) by(le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(txn_read_ops_bucket[15s])) by(le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(txn_read_ops_bucket[15s])) by(le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1.0, sum(irate(txn_read_ops_bucket[15s])) by(le))",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "Total Txn Write Ops",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(txn_write_ops_bucket[15s])) by(le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(txn_write_ops_bucket[15s])) by(le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(txn_write_ops_bucket[15s])) by(le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1.0, sum(irate(txn_write_ops_bucket[15s])) by(le))",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "Total Txn Scan Ops",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(txn_scan_ops_bucket[15s])) by(le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(txn_scan_ops_bucket[15s])) by(le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(txn_scan_ops_bucket[15s])) by(le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1.0, sum(irate(txn_scan_ops_bucket[15s])) by(le))",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "Total In-Flight Ops/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(in_flight_ops[15s]))/5"
    }
   ]
  },
  {
   "title": "Total In-Flight Ops/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(in_flight_ops[15s]))/5"
    }
   ]
  },
  {
   "title": "Txn Commit Count/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(txn_commit_count[15s]))/5"
    }
   ]
  },
  {
   "title": "Txn Abort Count/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(txn_abort_count[15s]))/5"
    }
   ]
  },
  {
   "title": "ThreadPool Task Duration (usec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(thread_pool_task_duration_bucket[15s])) by(le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(thread_pool_task_duration_bucket[15s])) by(le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(thread_pool_task_duration_bucket[15s])) by(le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1.0, sum(irate(thread_pool_task_duration_bucket[15s])) by(le))",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "ThreadPool Task Count/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(thread_pool_task_duration_count[15s]))/5"
    }
   ]
  },
  {
   "title": "GetSchema latency(usec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(gate_get_schema_latency_bucket[15s])) by(le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(gate_get_schema_latency_bucket[15s])) by(le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(gate_get_schema_latency_bucket[15s])) by(le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1.0, sum(irate(gate_get_schema_latency_bucket[15s])) by(le))",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "GetSchema Count/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(gate_get_schema_latency_count[15s]))/5"
    }
   ]
  },
  {
   "title": "CreateSchema latency(usec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(gate_create_schema_latency_bucket[15s])) by(le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(gate_create_schema_latency_bucket[15s])) by(le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(gate_create_schema_latency_bucket[15s])) by(le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1.0, sum(irate(gate_create_schema_latency_bucket[15s])) by(le))",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "CreateSchema Count/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(gate_create_schema_latency_count[15s]))/5"
    }
   ]
  },
  {
   "title": "CreateCollection latency(usec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(gate_create_collection_latency_bucket[15s])) by(le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(gate_create_collection_latency_bucket[15s])) by(le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(gate_create_collection_latency_bucket[15s])) by(le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1.0, sum(irate(gate_create_collection_latency_bucket[15s])) by(le))",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "CreateCollection Count/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(gate_create_collection_latency_count[15s]))/5"
    }
   ]
  },
  {
   "title": "CreateScanRequest latency(usec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(gate_create_scanread_latency_bucket[15s])) by(le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(gate_create_scanread_latency_bucket[15s])) by(le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(gate_create_scanread_latency_bucket[15s])) by(le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1.0, sum(irate(gate_create_scanread_latency_bucket[15s])) by(le))",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "CreateScanRequest Count/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(gate_create_scanread_latency_count[15s]))/5"
    }
   ]
  },
  {
   "title": "K2 RDMA Rx Batch Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "k2pg_rdma_stack_recv_batch_size{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "K2 RDMA Tx Batch Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "${component}_rdma_stack_send_batch_size{instance=~\"$host\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "K2 RDMA Rx Msg Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(${component}_rdma_stack_recv_count{instance=~\"$host\",job=~\"$job\"}[10m])"
    }
   ]
  },
  {
   "title": "K2 RDMA Tx Msg Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 135 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(${component}_rdma_stack_send_count{instance=~\"$host\",job=~\"$job\"}[10m])"
    }
   ]
  },
  {
   "title": "RDMA Tx GBits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 144 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_infiniband_port_data_transmitted_bytes_total{instance=~\"$host\"}[10m])*8/(1024*1024*1024)"
    }
   ]
  },
  {
   "title": "CPP Exceptions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 144 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(${component}_reactor_cpp_exceptions{job=~\"$job\"}[10m])"
    }
   ]
  },
  {
   "title": "RDMA packets TX/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_infiniband_port_packets_transmitted_total{device=\"mlx5_1\",instance=~\"$host\"}[30s])"
    }
   ]
  },
  {
   "title": "K2 RDMA Tx Queue Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "${component}_rdma_stack_send_queue_size{instance=~\"$host\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Network Rx Packet Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 162 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{instance=~\"$host\"}[10m])"
    }
   ]
  },
  {
   "title": "RDMA Rx GBits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 162 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_infiniband_port_data_received_bytes_total{instance=~\"$host\"}[10m])*8/(1024*1024*1024)"
    }
   ]
  },
  {
   "title": "Memory: malloc live objects",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 171 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "${component}_memory_malloc_live_objects{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "RDMA packets RX/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 171 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_infiniband_port_packets_received_total{device=\"mlx5_1\",instance=~\"$host\"}[30s])"
    }
   ]
  },
  {
   "title": "Memory: Malloc Ops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 180 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(${component}_memory_malloc_operations{job=~\"$job\"}[15s])"
    }
   ]
  },
  {
   "title": "Network Tx Packet Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 180 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets_total{instance=~\"$host\"}[10m])"
    }
   ]
  },
  {
   "title": "Memory: Cross CPU Frees",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 189 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(${component}_memory_cross_cpu_free_operations{job=~\"$job\"}[10m])"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 189 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "${component}_reactor_utilization{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Mem HugePages Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 198 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_HugePages_Total{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 198 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(${component}_reactor_cpu_busy_ms{job=~\"$job\"}[15s])"
    }
   ]
  },
  {
   "title": "Mem HugePages Rsvd",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 207 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_HugePages_Rsvd{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "CPU Steal Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 207 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(${component}_reactor_cpu_steal_time_ms{job=~\"$job\"}[15s])"
    }
   ]
  },
  {
   "title": "Mem HugePages  Free",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 216 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_HugePages_Free{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "% time spent in system calls",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 216 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{mode=\"system\",instance=~\"$host\"}[10m])"
    }
   ]
  },
  {
   "title": "Mem Cached GB",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 225 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$host\"}/(1024*1024*1024)"
    }
   ]
  },
  {
   "title": "% time spent in user space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 225 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{mode=\"user\",instance=~\"$host\"}[10m])"
    }
   ]
  },
  {
   "title": "CPU Scaling Frequency GHz",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 234 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz{instance=~\"$host\"}/1000000000"
    }
   ]
  }
 ]
}